boilerconnect-develop/johnslist/main/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from main import views

urlpatterns = [
    #user urls
    url(r'^user/?$', views.user_dash,name='user_dash'),
    url(r'^user/create/(?P<profile>[a-z]+)/?$', views.user_create,name='user_create'),
    url(r'^user/(?P<user_id>[0-9]+)/user_membership/?$', views.user_membership,name='user_membership'),
    url(r'^user/edit/?$', views.user_settings,name='user_settings'),
    #organization urls
    url(r'^organization/(?P<organization_id>[0-9]+)/dash/?$', views.organization_dash,name='organization_dash'),
    url(r'^organization/(?P<organization_id>[0-9]+)/?$', views.organization_detail,name='organization_detail'),
    url(r'^organization/create/?$', views.organization_create,name='organization_create'),
    url(r'^organization/(?P<organization_id>[0-9]+)/edit/?$', views.organization_settings,name='organization_settings'),
    #job urls
    url(r'^job/(?P<job_id>[0-9]+)/dash/?$', views.job_dash,name='job_dash'),
    url(r'^organization/(?P<organization_id>[0-9]+)/job/(?P<job_id>[0-9]+)/?$', views.jobrequest_dash,name='jobrequest_dash'),
    url(r'^job_creation$', views.job_creation,name='job_creation'),
    url(r'^job/(?P<job_id>[0-9]+)/edit/?$', views.job_settings,name='job_settings'),
    url(r'^ajax/change_status/$', views.ajax_change_status, name='ajax_change_status'),
    #misc urls
    url(r'^$',views.front_page,name='front_page'),
    url(r'^search/?$',views.search,name='search'),
    url(r'^login/?$', views.login,name='login'),
    url(r'^logout/?$', logout,{'template_name':'main/logout.html'},name='logout'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^quicksearch/?$', views.quicksearch,name='quicksearch'),
]

boilerconnect-develop/johnslist/main/models.py
from django.db import models
from django.forms import ModelForm,PasswordInput
from django.contrib.auth import forms
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_delete
from django.contrib.auth.models import User,Group
from guardian.shortcuts import assign_perm, remove_perm
from notifications.signals import notify
from django.core.urlresolvers import reverse

class UserProfile(models.Model):
    def __unicode__(self):
        return self.user.username

    # UserProfile - User
    user = models.OneToOneField(User,related_name = 'userprofile',null=True, blank = False)
    # purdueuser or communitypartner
    purdueuser = models.BooleanField(default=True, choices=((True, 'Purdue Professor'),(False, 'Community Agency')))
    # save which pages the user has visited before for the purposes of showing helpful dialogs
    visited_views = models.CharField(max_length=64,default="")
    first = models.CharField('firstname', max_length=128, null=True)
    last = models.CharField('lastname',max_length=128, null=True)
    organization = models.CharField('organization', max_length=128, null=True)
    title = models.CharField('title', max_length=128, null=True)
    phone = models.CharField('phone', max_length=128, null=True)


class CategoryGroup(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField('Service Category Group Name',max_length=64)
    description = models.TextField('Service Category Group Description')

class Category(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField('Service Category Name',max_length=64)
    description = models.TextField('Service Category Description',null=True)
    group = models.ForeignKey(CategoryGroup,related_name = 'categories')  # Category -= CategoryGroup

class Organization(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField('Organization Name',max_length=64)
    description = models.TextField('Organization Description')
    categories = models.ManyToManyField(Category, related_name = 'organizations')  # Category =-= Organization
    group = models.OneToOneField(Group) # Organization - Group
    url = models.URLField('Website', default="http://", blank=True)
    phone_number = models.CharField('Organization phone number',max_length=64)
    icon = models.ImageField(upload_to='organization', null=True)
    available = models.BooleanField(default=True,choices=((True, "Accepting Jobs"),(False, "Not accepting Jobs")))

    class Meta:
        permissions = (
            ( 'view_organization','Can view Organization' ),
            ( 'edit_organization','Can edit Organization' ),
            ( 'is_admin', 'Is an Administrator')
            )

    # get list of jobs accepted for Org
    def jobrequests_accepted(self):
        return JobRequest.objects.filter(organization = self,accepted = True,completed = False)

    # get list of jobs applied to by Org
    def jobrequests_applied(self):
        return JobRequest.objects.filter(organization = self,accepted = False, applied = True)

    # get list of jobs pending for Org
    def jobrequests_pending(self):
        return JobRequest.objects.filter(organization = self,accepted = False,declined = False)

    # get list of jobs declined by Org
    def jobrequests_declined(self):
        return JobRequest.objects.filter(organization = self,accepted = False,declined = True)

    # get list of jobs completed by Org
    def jobrequests_completed(self):
        return JobRequest.objects.filter(organization = self,completed = True)

    # get admins of this org
    def get_admins(self):
        return [user for user in self.group.user_set.all() if user.has_perm('is_admin',self)]


@receiver(post_save, sender=Organization)
def add_perms_organization(sender,**kwargs):
    # check if this post_save signal was generated from a Model create (vs a Model edit)
    if 'created' in kwargs and kwargs['created']:
        organization=kwargs['instance']

        # allow organization to view and edit itself by default
        assign_perm('view_organization',organization.group,organization)
        assign_perm('edit_organization',organization.group,organization)

class Job(models.Model):
    def __unicode__(self):
        return self.name
    name = models.CharField('Job Name',max_length=128)
    # when the job was created
    date_created = models.DateTimeField('Date Created', auto_now=True)
    # what entity/organization needs this job?
    client_organization = models.CharField('What organization do you represent?', max_length=64)
    # short description
    description = models.TextField('Job Description', max_length=256)
    # end product to be delivered
    deliverable = models.TextField('Deliverable', max_length=256)
    # when Job is due for completion
    duedate = models.DateTimeField('Date Due')
    # all persons who may be affected by project
    #stakeholders = models.TextField('Stakeholders')
    # important technical requirements
    #additional_information = models.TextField('Additional Information', blank = True)
    # budget estimate
    #budget = models.CharField('Budget', max_length=64)
    # file attachments
    #attachments = models.FileField(upload_to='job', blank = True)
    creator = models.ForeignKey(User,related_name = 'jobs')
    organizations = models.ManyToManyField(Organization, through = 'JobRequest', blank=False, null=True)
    #organizations = models.CharField(default="nothing",null=True,max_length = 256)
    contact_information = models.CharField('Contact Information', max_length = 256, blank = False, null=True)
    skill_required = models.CharField('Volunteer skills required', max_length=256, blank = False, null=True)
    hours_day = models.CharField('Number of hours per day', max_length=256, blank = False, null=True)
    #  Job is closed after a jr is confirmed
    closed = models.BooleanField(default = False)
    # some tags to determine what organizations to submit job to
    categories = models.ManyToManyField(Category, related_name = 'jobs')
    #categories = models.CharField(default="nothing",null=True, max_length = 256)
    status = models.IntegerField(default = 0, choices = ((0, 'Pending'), (1, 'Approved'), (2, 'Disapproved'), (3, 'Closed')))
    active = models.BooleanField(default = False)
    class Meta:
        permissions = (
            ( 'view_job','Can view Job' ),
            ( 'edit_job','Can edit Job'),
            ( 'is_creator', 'Is a creator of Job')
            )

    # returns JobRequests that have been accepted
    def jobrequests_accepted(self):
        accepted = JobRequest.objects.filter(job = self, accepted = True)
        return accepted
    # returns JobRequests that have been applied to
    def jobrequests_applied(self):
        applied = JobRequest.objects.filter(job = self, accepted = False, applied = True)
        return applied
    # returns JobRequests that are pending
    def jobrequests_pending(self):
        pending = JobRequest.objects.filter(job = self, accepted = False, declined = False, completed = False)
        return pending
    # returns JobRequests that have been declined
    def jobrequests_declined(self):
        declined = JobRequest.objects.filter(job = self, declined = True)
        return declined
    # creates a new JobRequest
    def request_organization(self,organization):
        jr = JobRequest.objects.create(job = self,organization = organization);
        return jr

# add default job permissions
@receiver(post_save, sender=Job)
def add_perms_job(sender,**kwargs):
    # check if this post_save signal was generated from a Model create
    job=kwargs['instance']
    if 'created' in kwargs and kwargs['created']:

        # allow creator to view and edit job
        assign_perm('view_job',job.creator,job)
        assign_perm('edit_job',job.creator,job)
        # allow requested orgs to view job
        for org in job.organizations.all():
            assign_perm('view_job',org.group,job)
    else:
        # notify users of changed JobRequest
        if job.closed:
            jobrequests = job.jobrequests_accepted()
        else:
            jobrequests = job.jobrequests_accepted() | job.jobrequests_pending()
        for jobrequest in jobrequests:
            notify.send(job.creator,
                        verb="modified",
                        action_object=jobrequest,
                        recipient=jobrequest.organization.group,
                        url=reverse('organization_dash',
                                    kwargs = {'organization_id':jobrequest.organization.id})+
                                    "?jobrequestID="+str(jobrequest.id)
                        )


class JobRequest(models.Model):
    def __unicode__(self):
        return self.job.name

    job = models.ForeignKey(Job,related_name = 'jobrequests') # Job -= JobRequest
    organization = models.ForeignKey(Organization)
    applied = models.NullBooleanField(default = False)
    accepted = models.NullBooleanField(default = False)	
    declined = models.NullBooleanField(default = False)
    confirmed = models.NullBooleanField(default = False)
    completed = models.NullBooleanField(default = False)

    class Meta:
            permissions = (
                ( 'view_jobrequest','Can view JobRequest' ),
                ( 'edit_jobrequest','Can edit JobRequest'),
                ( 'edit_jobrequest_state','Can edit JobRequest state'),
                )
    # set a JobRequest as applied
    def apply(self):
        self.accepted = False
        self.applied = True
        self.declined = False
        self.save()
        notify.send(self.organization,
                    verb="applied",
                    action_object=self.job,
                    recipient=self.job.creator,
                    url=reverse('job_dash',
                                kwargs={'job_id': self.job.id}) +

boilerconnect-develop/johnslist/main/templates/widgets/category_select.html
{% load staticfiles %}

<div style="display: none;">
</div>

<div class="panel-group">
    <ul id="id_categories">
        {% comment %} Display each category group and its categories in a panel {% endcomment %}
        {% for category_group in category_groups %}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse{{forloop.counter}}">{{category_group.name}}</a>
                </h4>
            </div>
            {% comment %}collapsing disabled for now {% endcomment %}
            {% comment %}<div id="collapse{{forloop.counter}}" class="panel-collapse collapse">{% endcomment %}
            <div id="collapse{{forloop.counter}}" class="panel-collapse ">
                    {% for category in category_group.categories.all %}
                    <div class="checkbox">
                        <label>
                        </label>
                        <!-- <li> -->
                        <label for="id_categories_{{category.id}}">
                            <input id="id_categories_{{category.id}}" name="categories" type="checkbox" value="{{category.id}}" {% if category in selected_categories %}checked{% endif %}>
                            {{category.name}}
                        </label>
                            <!-- </li> -->
                    </div>
                    {% endfor %}
            </div>
        </div>
        {% endfor %}
    </ul>
</div>

boilerconnect-develop/johnslist/main/templates/widgets/org_search.html
{% load staticfiles %}
<!-- ---------------------------- Organization Search ----------------------------->

<div style="display: none;">
    <select multiple="multiple" id="id_organizations" name="organizations">
        {% for organization in selected_orgs %}
        <option value="{{organization.id}}" selected="selected">{{organization.name}}</option>
        {% endfor %}
        {% for organization in deselected_orgs %}
        <option value="{{organization.id}}">{{organization.name}}</option>
        {% endfor %}
    </select>
</div>

<div class="row org_search">
    <div class="col-sm-6">
    <h2>Search Organizations</h2>
    Additionally, you can request work from specific groups.  Search groups and add them below.
    <div class="form-group">
    <input id="search" class="form-control input-lg" type="text" >
    </div>
        <div class="org_list list-group" id="org_results">
            {% for org in deselected_orgs %}
            <div class="org_item list-group-item" org_pk="{{org.id}}">
                <h4 class="org_name list-group-item-heading">
                <a href="{% url 'organization_detail' org.id %}">
                {{org.name}}
                </a>
                <a onclick="select_org(this);" class="org_button btn btn-success pull-right">Add</a>
                </h4>
                <p>
                {% for cat in org.categories.all %}
                <span class="category btn btn-default">{{ cat }}</span>
                {% endfor %}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="col-sm-6">
        <h2>Selected Organizations</h2>
        <div class="org_list list-group" id="org_selected">
            {% for org in selected_orgs %}
            <div class="org_item list-group-item" org_pk="{{org.id}}">
                <h4 class="org_name list-group-item-heading">
                <a href="{% url 'organization_detail' org.id %}">
                {{org.name}}
                </a>
                <a onclick="deselect_org(this);" class="org_button btn btn-danger pull-right">Remove</a>
                </h4>
                <p>
                {% for cat in org.categories.all %}
                <span class="category btn btn-default">{{ cat }}</span>
                {% endfor %}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<script src="{% static 'org_search.js' %}"></script>